### ISSUE TITLE
Issues with rebase-helper

### ISSUE THREAD

**Issue by ralphbean** [fedora-infra/the-new-hotness#102]
I've been trying to get a local test of the new rebase-helper integration working locally, but I keep running into oddities.  The latest one has me stumped:

```
[2016-02-22 21:48:24][    fedmsg    INFO] Handling anitya msg u'2016-6f9bafba-8720-4474-a81f-58fb4984fb13'                                         
[2016-02-22 21:48:34][    fedmsg    INFO] /home/threebean/devel/the-new-hotness                                                                    
[2016-02-22 21:48:34][    fedmsg    INFO] Running '/usr/bin/dnf repoquery --config ./yum-config --quiet --all --qf %{name}\t%{version}\t%{release}'
[2016-02-22 21:52:17][    fedmsg    INFO] Rebuilt nvr_dict with 44143 entries                                                                      
[2016-02-22 21:52:17][    fedmsg    INFO] Comparing upstream 4.2.1 against repo 4.2-2.fc24                                                         
[2016-02-22 21:52:17][    fedmsg    INFO] OK, 4.2.1 is newer than 4.2-2.fc24                                                                       
[2016-02-22 21:52:55][    fedmsg    INFO] Created bug: #1262388 NEW        - praiskup@redhat.com - PyGreSQL-4.2.1 is available                     
[2016-02-22 21:52:55][    fedmsg    INFO] Filed new bug 'https://partner-bugzilla.redhat.com/show_bug.cgi?id=1262388'                              
[2016-02-22 21:52:55][    fedmsg    INFO] publishing topic 'update.bug.file'                                                                       
[2016-02-22 21:52:55][    fedmsg    INFO] Rebase-helper is going to rebase package                                                                 
[2016-02-22 21:52:55][    fedmsg    INFO] Cloning 'http://pkgs.fedoraproject.org/cgit/rpms/PyGreSQL.git' to '/var/tmp/thn-rh97afZh'                
usage: fedmsg-hub [-h] [-v] [-p] [-b] [--buildtool BUILDTOOL]                                                                                      
                  [--pkgcomparetool PKGCOMPARETOOL] [--outputtool OUTPUTTOOL]                                                                      
                  [-w] [--not-download-sources] [-c] [--non-interactive]                                                                           
                  [--comparepkgs-only COMPAREPKGS]                                                                                                 
                  SOURCES                                                                                                                          
fedmsg-hub: error: unrecognized arguments: --builds-nowait                                                                                         
Unhandled Error                                                                                                                                    
Traceback (most recent call last):                                                                                                                 
  File "/usr/lib64/python2.7/threading.py", line 786, in __bootstrap                                                                               
    self.__bootstrap_inner()                                                                                                                       
  File "/usr/lib64/python2.7/threading.py", line 813, in __bootstrap_inner                                                                         
    self.run()                                                                                                                                     
  File "/usr/lib64/python2.7/threading.py", line 766, in run                                                                                       
    self.__target(*self.__args, **self.__kwargs)                                                                                                   
--- <exception caught here> ---                                                                                                                    
  File "/usr/lib64/python2.7/site-packages/twisted/python/threadpool.py", line 196, in _worker                                                     
    result = context.call(ctx, function, *args, **kwargs)                                                                                          
  File "/usr/lib64/python2.7/site-packages/twisted/python/context.py", line 118, in callWithContext                                                
    return self.currentContext().callWithContext(ctx, func, *args, **kw)                                                                           
  File "/usr/lib64/python2.7/site-packages/twisted/python/context.py", line 81, in callWithContext                                                 
    return func(*args,**kw)                                                                                                                        
  File "/usr/lib/python2.7/site-packages/moksha/hub/api/consumer.py", line 191, in _work                                                           
    self.consume(message)                                                                                                                          
  File "/home/threebean/devel/the-new-hotness/hotness/consumers.py", line 152, in consume                                                          
    self.handle_anitya_version_update(msg)                                                                                                         
  File "/home/threebean/devel/the-new-hotness/hotness/consumers.py", line 193, in handle_anitya_version_update                                     
    self._handle_anitya_update(upstream, pname, msg)                                                                                               
  File "/home/threebean/devel/the-new-hotness/hotness/consumers.py", line 273, in _handle_anitya_update                                            
    result_rh, rh_stuff = self.buildsys.rebase_helper(package, upstream, tmp, bz)                                                                  
  File "/home/threebean/devel/the-new-hotness/hotness/buildsys.py", line 183, in rebase_helper                                                     
    cli = CLI(argument)                                                                                                                            
  File "/usr/lib/python2.7/site-packages/rebasehelper/cli.py", line 40, in __init__                                                                
    self.args = self.parser.parse_args(args)                                                                                                       
  File "/usr/lib64/python2.7/argparse.py", line 1704, in parse_args                                                                                
    self.error(msg % ' '.join(argv))                                                                                                               
  File "/usr/lib64/python2.7/argparse.py", line 2374, in error                                                                                     
    self.exit(2, _('%s: error: %s\n') % (self.prog, message))                                                                                      
  File "/usr/lib64/python2.7/argparse.py", line 2362, in exit                                                                                      
    _sys.exit(status)                                                                                                                              
exceptions.SystemExit: 2                                                                                                                           
```

**Comment by phracek** [comment]
@ralphbean What version of rebase-helper do you have? rebase-helper 0.7.1 at least.
Version 0.7.1 introduces the option.
EPEL-7 build http://koji.fedoraproject.org/koji/buildinfo?buildID=737683
FEdora 22 build http://koji.fedoraproject.org/koji/buildinfo?buildID=737681
Fedora 23 build http://koji.fedoraproject.org/koji/buildinfo?buildID=737678

**Comment by ralphbean** [comment]
Ah ha!  I only had rebase-helper-0.7.0 in place on my F23 system.  Will update and try again.

**Comment by phracek** [comment]
Great. Hopefully it will be fixed. I have tested it one more and all works fine.

**Comment by ralphbean** [comment]
Yes!  It works :)

I have one small proposed change in #103 if you'd like to take a look.  Once we figure out whether or not to merge that, I'll cut a release and we can try this all in the Fedora Infrastructure staging environment.  Looking forwards to your feedback!
