### ISSUE TITLE
Failed to download the sources, but didn't realize it until the SRPM build failed

### ISSUE THREAD

**Issue by jeremycline** [fedora-infra/the-new-hotness#159]
Staging hotness produced:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/hotness/consumers.py", line 338, in _handle_anitya_update
    package, upstream, version, bz)
  File "/usr/lib/python2.7/site-packages/hotness/buildsys.py", line 184, in handle
    ['rpmbuild', '-D', '_sourcedir .', '-D', '_topdir .', '-bs', specfile], cwd=tmp)
  File "/usr/lib/python2.7/site-packages/hotness/buildsys.py", line 121, in run
    raise Exception(message % (' '.join(cmd), p.returncode, out, err))
Exception: cmd:  rpmbuild -D _sourcedir . -D _topdir . -bs /var/tmp/thn-J1zGit/rubygem-bundler.spec
return code:  1
stdout:


RPM build errors:

stderr:
error: Bad file: ./bundler-1.14.4-specs.tgz: No such file or directory
    Bad file: ./bundler-1.14.4-specs.tgz: No such file or directory
```
We should never get to the point where we're building the SRPM if we don't have the sources.

**Comment by Zlopez** [comment]
## Implementation details
After implementation of https://github.com/fedora-infra/the-new-hotness/issues/189 this will need to be uploaded to lookaside cache. See https://pagure.io/fedora-infrastructure/issue/7688 for more.

**Comment by Zlopez** [comment]
We should use [packit.distgit](https://github.com/packit-service/packit/blob/master/packit/distgit.py#L229) for this.

**Comment by Zlopez** [comment]
This can't be reproduced and it's two years old. So I'm closing this.
