### ISSUE TITLE
Gracefully handle pkgdb being down

### ISSUE THREAD

**Issue by jeremycline** [fedora-infra/the-new-hotness#165]
Yesterday pkgdb was stopped as part of the mass branching. We don't handle that very well:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/moksha/hub/api/consumer.py", line 191, in _work
    self.consume(message)
  File "/usr/lib/python2.7/site-packages/hotness/consumers.py", line 200, in consume
    self.handle_buildsys_real(msg)
  File "/usr/lib/python2.7/site-packages/hotness/consumers.py", line 432, in handle_buildsys_real
    rawhide = self.get_dist_tag()
  File "/usr/lib/python2.7/site-packages/dogpile/cache/region.py", line 1053, in decorate
    should_cache_fn)
  File "/usr/lib/python2.7/site-packages/dogpile/cache/region.py", line 657, in get_or_create
    async_creator) as value:
  File "/usr/lib/python2.7/site-packages/dogpile/core/dogpile.py", line 158, in __enter__
    return self._enter()
  File "/usr/lib/python2.7/site-packages/dogpile/core/dogpile.py", line 98, in _enter
    generated = self._enter_create(createdtime)
  File "/usr/lib/python2.7/site-packages/dogpile/core/dogpile.py", line 149, in _enter_create
    created = self.creator()
  File "/usr/lib/python2.7/site-packages/dogpile/cache/region.py", line 625, in gen_value
    created_value = creator()
  File "/usr/lib/python2.7/site-packages/dogpile/cache/region.py", line 1049, in creator
    return fn(*arg, **kw)
  File "/usr/lib/python2.7/site-packages/hotness/consumers.py", line 730, in get_dist_tag
    raise IOError('URL %s returned code %s', r.url, r.status_code)
IOError: [Errno URL %s returned code %s] https://admin.fedoraproject.org/pkgdb/api/collections/master/: 503
```
It'd be good to log the event and note on the bugzilla that we didn't build the package because pkgdb was down.

**Comment by Zlopez** [comment]
pkgdb is no longer used.
