### ISSUE TITLE
no bug filed for remoto-1.0.0

### ISSUE THREAD

**Issue by ktdreyer** [fedora-infra/the-new-hotness#220]
I looked in [datagrepper](https://apps.fedoraproject.org/datagrepper/raw?category=hotness&delta=2592000) but I cannot find a message about remoto 1.0.0.

release-monitoring.org says it retrieved version 1.0.0 on 2019-02-13 22:03 , https://release-monitoring.org/project/3993/ , but datagrepper does not have a record about remoto at that time.

**Comment by Zlopez** [comment]
13.2.2019 bugzilla returned a 503 error few times and the-new-hotness couldn't log in afterwards. I applied a fix for this afterwards, but most of the updates made on 13.2.2019 were lost and remoto was one of them.

```
Message
-------
[2019-02-13 22:03:35][fedmsg.consumers   ERROR]
```python
{'body': {u'username': u'anitya', u'certificate': u'LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUUzRENDQkVXZ0F3SUJBZ0lDQXBvd0RRWUpL\nb1pJaHZjTkFRRUxCUUF3Z2FBeEN6QUpCZ05WQkFZVEFsVlQKTVFzd0NRWURWUVFJRXdKT1F6RVFN\nQTRHQTFVRUJ4TUhVbUZzWldsbmFERVhNQlVHQTFVRUNoTU9SbVZrYjNKaApJRkJ5YjJwbFkzUXhE\nekFOQmdOVkJBc1RCbVpsWkcxelp6RVBNQTBHQTFVRUF4TUdabVZrYlhObk1ROHdEUVlEClZRUXBF\nd1ptWldSdGMyY3hKakFrQmdrcWhraUc5dzBCQ1FFV0YyRmtiV2x1UUdabFpHOXlZWEJ5YjJwbFkz\nUXUKYjNKbk1CNFhEVEU0TURreU5URTRNakV3TVZvWERUSTRNRGt5TWpFNE1qRXdNVm93Z2VZeEN6\nQUpCZ05WQkFZVApBbFZUTVFzd0NRWURWUVFJRXdKT1F6RVFNQTRHQTFVRUJ4TUhVbUZzWldsbmFE\nRVhNQlVHQTFVRUNoTU9SbVZrCmIzSmhJRkJ5YjJwbFkzUXhEekFOQmdOVkJBc1RCbVpsWkcxelp6\nRXlNREFHQTFVRUF4TXBjbVZzWldGelpTMXQKYjI1cGRHOXlhVzVuTFhKbGJHVmhjMlV0Ylc5dWFY\nUnZjbWx1Wnk1dmNtY3hNakF3QmdOVkJDa1RLWEpsYkdWaApjMlV0Ylc5dWFYUnZjbWx1WnkxeVpX\neGxZWE5sTFcxdmJtbDBiM0pwYm1jdWIzSm5NU1l3SkFZSktvWklodmNOCkFRa0JGaGRoWkcxcGJr\nQm1aV1J2Y21Gd2NtOXFaV04wTG05eVp6Q0NBU0l3RFFZSktvWklodmNOQVFFQkJRQUQKZ2dFUEFE\nQ0NBUW9DZ2
 dFQkFLbkE5TkUvNEprcDVWZTM3SC8vWGRmZDVLeHBzQUtVamZpT1RTY2ZwRHVmM04x\nRApJL1BOK3F1dXFJaWhpaFc0NGJlei9IZGlja1FnNEkxZklxYWpiZkV2WEplcTJUOXJ4RFkvcUFO\nRGxCalRnQlF6Cmd5WG1wclMrUjFiSWhiZ3ZMamNBN0g4bDVhYWhQQnI5aWE0N1M4Y25hVXB1d2FE\nbUl1cjYvV2ZsVlk1b2pmMGwKNzFPSGVmY1RueURpVGZlYzVGaCsxRWRUaVRIR0NaaDV5czB1bUta\nc1IxUHB3TDdaUW1va0NaV2V2NEU3aVBRaAo3NDNPaWRhWGdxVm5yak54bmZveDNkOUZwU2FaOXVu\nd0RHUjJVS3VUbkxLM21CRUpTNTBvZ0dNVmp5M09xL2hDCjJvejBzcisrRk9XM0FxamZkUGtvWmdi\neXRhQ0ZSM3ZuK0VmZ25BRUNBd0VBQWFPQ0FWY3dnZ0ZUTUFrR0ExVWQKRXdRQ01BQXdMUVlKWUla\nSUFZYjRRZ0VOQkNBV0hrVmhjM2t0VWxOQklFZGxibVZ5WVhSbFpDQkRaWEowYVdacApZMkYwWlRB\nZEJnTlZIUTRFRmdRVVloOEk0Y29MRDk2Z2lmOUxXRDZPTHpSSnlWVXdnZFVHQTFVZEl3U0J6VENC\nCnlvQVVhMEJhK1JJSWlWbm5XZVVGOVFJZENrNS9GQUNoZ2Fha2dhTXdnYUF4Q3pBSkJnTlZCQVlU\nQWxWVE1Rc3cKQ1FZRFZRUUlFd0pPUXpFUU1BNEdBMVVFQnhNSFVtRnNaV2xuYURFWE1CVUdBMVVF\nQ2hNT1JtVmtiM0poSUZCeQpiMnBsWTNReER6QU5CZ05WQkFzVEJtWmxaRzF6WnpFUE1BMEdBMVVF\nQXhNR1ptVmtiWE5uTVE4d0RRWURWUVFwCkV3Wm1aV1J0YzJjeEpqQWtCZ2txaGtpRzl3MEJ
 DUUVX\nRjJGa2JXbHVRR1psWkc5eVlYQnliMnBsWTNRdWIzSm4KZ2drQTQxQWVSMDhYSGtVd0V3WURWUjBs\nQkF3d0NnWUlLd1lCQlFVSEF3SXdDd1lEVlIwUEJBUURBZ2VBTUEwRwpDU3FHU0liM0RRRUJDd1VB\nQTRHQkFMQXNYS1JXMVBEUHNXYTd6dEdQejdiRzBkQnF3eHJFa0NoL2tIMkd2dGtPCjNyQWJCNnZt\nRUtFU2o1VHNnVVZKMGsyY2FLRCsxWEdwdUoxQXZRTWF1VTZxaDVOM29JajNDbS9XN0c3b0NRSnEK\nLzhEeTMvYW9DdFBEWE1KYkVtUnp0Rll3RXMyOWdHenpOMHFicFVOVExodzdqL2k0ZUV6QnRzbEVQ\nNUg2L2RiSAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==\n', u'i': 1, u'timestamp': 1550095413, u'msg_id': u'2019-912be4b1-40d5-4844-aa6b-b6894a843724', u'crypto': u'x509', u'topic': u'org.release-monitoring.prod.anitya.project.version.update', u'signature': u'mHI1SbX/n+V1hWnIpH4kPVf70PHGj6tRIxaQWye70d4WLCVK5X89fh+BAsXfJlGxmnfxovtEQGLv\n8UNC0HVDCjx5w3rtuJGX6WCIb697cKmsKgoBwmX05p4p0edyNdCh3Q38eGL3bSCzmgMWwl7qnjbL\nZQTFOe00OxNwawxemL8rbRJNyEPIq84X+vgZX91egkKC/SZmApPpccHB64BLGQoxAGNr62h8AU7R\nAT0E/719w/oxdMDw5luWvtHWLCNpXm95pzIpKjgx6ZneiJxRdm2qFiMpHdeyOpfszAWJjq3Ox1k/\nubGFUWYMIxV6RFobpqIBGUYnxGJknP8d82M
 jRw==\n', u'msg': {u'project': {u'regex': None, u'name': u'remoto', u'versions': [u'1.0.0', u'0.0.35', u'0.0.34', u'0.0.33', u'0.0.32', u'0.0.31', u'0.0.30', u'0.0.29', u'0.0.28', u'0.0.27', u'0.0.26', u'0.0.25', u'0.0.24', u'0.0.23', u'0.0.22', u'0.0.21', u'0.0.20', u'0.0.19', u'0.0.18', u'0.0.17', u'0.0.16', u'0.0.14', u'0.0.13', u'0.0.12', u'0.0.11', u'0.0.10', u'0.0.9', u'0.0.8', u'0.0.7', u'0.0.6', u'0.0.5', u'0.0.4', u'0.0.3', u'0.0.2', u'0.0.1'], u'ecosystem': u'pypi', u'created_on': 1412175084.0, u'version': u'1.0.0', u'version_url': None, u'updated_on': 1550095413.0, u'homepage': u'https://pypi.python.org/pypi/remoto', u'id': 3993, u'backend': u'PyPI'}, u'message': {u'versions': [u'1.0.0', u'0.0.35', u'0.0.34', u'0.0.33', u'0.0.32', u'0.0.31', u'0.0.30', u'0.0.29', u'0.0.28', u'0.0.27', u'0.0.26', u'0.0.25', u'0.0.24', u'0.0.23', u'0.0.22', u'0.0.21', u'0.0.20', u'0.0.19', u'0.0.18', u'0.0.17', u'0.0.16', u'0.0.14', u'0.0.13', u'0.0.12', u'0.0.11', u'0.0.10', u'0.0.9', u'0.
 0.8', u'0.0.7', u'0.0.6', u'0.0.5', u'0.0.4', u'0.0.3', u'0.0.2', u'0.0.1'], u'ecosystem': u'pypi', u'old_version': u'0.0.35', u'upstream_version': u'1.0.0', u'project': {u'regex': None, u'name': u'remoto', u'versions': [u'1.0.0', u'0.0.35', u'0.0.34', u'0.0.33', u'0.0.32', u'0.0.31', u'0.0.30', u'0.0.29', u'0.0.28', u'0.0.27', u'0.0.26', u'0.0.25', u'0.0.24', u'0.0.23', u'0.0.22', u'0.0.21', u'0.0.20', u'0.0.19', u'0.0.18', u'0.0.17', u'0.0.16', u'0.0.14', u'0.0.13', u'0.0.12', u'0.0.11', u'0.0.10', u'0.0.9', u'0.0.8', u'0.0.7', u'0.0.6', u'0.0.5', u'0.0.4', u'0.0.3', u'0.0.2', u'0.0.1'], u'ecosystem': u'pypi', u'created_on': 1412175084.0, u'version': u'1.0.0', u'version_url': None, u'updated_on': 1550095413.0, u'homepage': u'https://pypi.python.org/pypi/remoto', u'id': 3993, u'backend': u'PyPI'}, u'agent': u'anitya', u'packages': [{u'package_name': u'python-remoto', u'distro': u'Fedora'}], u'odd_change': False}, u'distro': None}}, 'topic': u'org.release-monitoring.prod.anitya.proj
 ect.version.update'}
```


Process Details
---------------
- host:     hotness01.phx2.fedoraproject.org
- PID:      22045
- name:     fedmsg-hub
- command:  /usr/bin/python2 /usr/bin/fedmsg-hub
- msg_id:   

Callstack that lead to the logging statement
--------------------------------------------
```python
  File "/usr/lib64/python2.7/threading.py", line 785 in __bootstrap
    self.__bootstrap_inner()
  File "/usr/lib64/python2.7/threading.py", line 812 in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 765 in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib64/python2.7/site-packages/twisted/python/threadpool.py", line 167 in _worker
    result = context.call(ctx, function, *args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/twisted/python/context.py", line 118 in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib64/python2.7/site-packages/twisted/python/context.py", line 81 in callWithContext
    return func(*args,**kw)
  File "/usr/lib/python2.7/site-packages/moksha/hub/api/consumer.py", line 186 in _work_loop
    self._do_work(message)
  File "/usr/lib/python2.7/site-packages/moksha/hub/api/consumer.py", line 210 in _do_work
    self.log.exception(message)
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/moksha/hub/api/consumer.py", line 207, in _do_work
    self.consume(message)
  File "/usr/lib/python2.7/site-packages/hotness/consumers.py", line 171, in consume
    self.handle_anitya_version_update(msg)
  File "/usr/lib/python2.7/site-packages/hotness/consumers.py", line 213, in handle_anitya_version_update
    self._handle_anitya_update(upstream, pname, msg)
  File "/usr/lib/python2.7/site-packages/hotness/consumers.py", line 283, in _handle_anitya_update
    projectid, package, upstream, version, release, url)
  File "/usr/lib/python2.7/site-packages/hotness/bz.py", line 113, in handle
    bug = self.create_bug(**kwargs)
  File "/usr/lib/python2.7/site-packages/hotness/bz.py", line 250, in create_bug
    new_bug = self.bugzilla.createbug(**bug_dict)
  File "/usr/lib/python2.7/site-packages/bugzilla/base.py", line 1741, in createbug
    rawbug = self._proxy.Bug.create(data)
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1233, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/site-packages/bugzilla/transport.py", line 104, in _ServerProxy__request
    self)._ServerProxy__request(methodname, params)
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1591, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/site-packages/bugzilla/transport.py", line 201, in request
    return self._request_helper(url, request_body)
  File "/usr/lib/python2.7/site-packages/bugzilla/transport.py", line 179, in _request_helper
    return self.parse_response(response)
  File "/usr/lib/python2.7/site-packages/bugzilla/transport.py", line 154, in parse_response
    return unmarshaller.close()
  File "/usr/lib64/python2.7/xmlrpclib.py", line 794, in close
    raise Fault(**self._stack[0])
Fault: <Fault 410: 'You must log in before using this part of Red Hat Bugzilla.'>
```

So I'm closing this as fixed, but I'm sorry this happened.
