### ISSUE TITLE
Production openshift - TypeError in _validate_spec_urls

### ISSUE THREAD

**Issue by Zlopez** [fedora-infra/the-new-hotness#241]
There is issue when creating scratch build in OpenShift.

```
[fedora_messaging.twisted.protocol INFO] Consuming message from topic org.release-monitoring.prod.anitya.project.version.update (message id 7fa3163e-f61b-4e2e-ad7a-f6b4325f137f)
[hotness.consumers INFO] Handling anitya msg '7fa3163e-f61b-4e2e-ad7a-f6b4325f137f'
[hotness.consumers INFO] Comparing upstream 3.2.0 against repo 3.1.0-1.fc31
[hotness.consumers INFO] OK, 3.2.0 is newer than 3.1.0-1.fc31
[hotness.bz INFO] Found and updating bug 'https://bugzilla.redhat.com/show_bug.cgi?id=1700117' 
[hotness.bz INFO] Comparing '3.1.0', '3.2.0'
[hotness.bz INFO] Updated bug: https://bugzilla.redhat.com/show_bug.cgi?id=1700117 
[hotness.consumers INFO] publishing topic 'update.bug.file'
[hotness.consumers INFO] Filed Bugzilla #1700117
[hotness.consumers INFO] Starting scratch build for qalculate-gtk
[hotness.buildsys INFO] Cloning 'https://src.fedoraproject.org/rpms/qalculate-gtk.git'  to '/var/tmp/thn-wcoxkb17'
[hotness.consumers ERROR] startswith first arg must be bytes or a tuple of bytes, not str 
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/hotness/consumers.py", line 304, in _handle_anitya_update
    package, upstream, version, bz
  File "/usr/local/lib/python3.7/site-packages/hotness/buildsys.py", line 347, in handle
    new_sources = spec_sources(specfile, tmp)
  File "/usr/local/lib/python3.7/site-packages/hotness/buildsys.py", line 517, in spec_sources
    _validate_spec_urls(specfile_path)
  File "/usr/local/lib/python3.7/site-packages/hotness/buildsys.py", line 479, in _validate_spec_urls
    if line.startswith("Source"):
TypeError: startswith first arg must be bytes or a tuple of bytes, not str 
[hotness.bz INFO] Followed up on bug: https://bugzilla.redhat.com/show_bug.cgi?id=1700117 
[fedora_messaging.twisted.protocol INFO] Successfully consumed message from topic org.release-monitoring.prod.anitya.project.version.update (message id 7fa3163e-f61b-4e2e-ad7a-f6b4325f137f)
```

**Comment by Zlopez** [comment]
Fixed by #242
