### ISSUE TITLE
Crash on proxy error

### ISSUE THREAD

**Issue by Zlopez** [fedora-infra/the-new-hotness#269]
the-new-hotness is crashing when proxy error occurs when downloading sources.
```
[fedora_messaging.twisted.protocol INFO] Consuming message from topic org.release-monitoring.prod.anitya.project.version.update (message id ccb39e62-a598-496a-9f50-1d13241fe796)
[hotness.consumers INFO] Handling anitya msg 'ccb39e62-a598-496a-9f50-1d13241fe796'
[hotness.consumers INFO] Comparing upstream 2.42.3 against repo 2.42.2-1.fc32
[hotness.consumers INFO] OK, 2.42.3 is newer than 2.42.2-1.fc32
[bugzilla.bug INFO] Bug 1777328 missing attribute 'bug_status' - doing implicit refresh(). This will be slow, if you want to avoid this, properly use query/getbug include_fields, and set bugzilla.bug_autorefresh = False to force failure.
[hotness.bz INFO] Created bug: #1777328 NEW        - me@zygoon.pl - snapd-2.42.3 is available
[hotness.bz INFO] Filed new bug 'https://bugzilla.redhat.com/show_bug.cgi?id=1777328'
[hotness.consumers INFO] publishing topic 'update.bug.file'
[hotness.consumers INFO] Filed Bugzilla #1777328
[hotness.consumers INFO] Starting scratch build for snapd
[hotness.buildsys INFO] Cloning 'https://src.fedoraproject.org/rpms/snapd.git' to '/var/tmp/thn-51otunij'
 % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
[fedora_messaging.twisted.protocol ERROR] Received unexpected exception from consumer Consumer(queue=the-new-hotness, callback=<hotness.consumers.BugzillaTicketFiler object at 0x7fc29cd11908>)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/hotness/buildsys.py", line 520, in spec_sources
    output = sp.check_output(["spectool", "-g", specfile_path], cwd=target_dir)
  File "/usr/lib64/python3.7/subprocess.py", line 376, in check_output
    **kwargs).stdout
  File "/usr/lib64/python3.7/subprocess.py", line 468, in run
   output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['spectool', '-g', '/var/tmp/thn-51otunij/snapd.spec']' returned non-zero exit status 22.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/hotness/consumers.py", line 314, in _handle_anitya_update
    package, upstream, version, bz
  File "/usr/local/lib/python3.7/site-packages/hotness/buildsys.py", line 347, in handle
    new_sources = spec_sources(specfile, tmp)
  File "/usr/local/lib/python3.7/site-packages/hotness/buildsys.py", line 561, in spec_sources
    raise exceptions.DownloadException(msg)
hotness.exceptions.DownloadException: An HTTP error occurred downloading the package's new Source URLs: Getting https://github.com/snapcore/snapd/releases/download/2.42.3/snapd_2.42.3.only-vendor.tar.xz to ./snapd_2.42.3.only-vendor.tar.xz

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/fedora_messaging/twisted/protocol.py", line 239, in _read
    yield threads.deferToThread(consumer.callback, message)
  File "/usr/lib64/python3.7/site-packages/twisted/python/threadpool.py", line 250, in inContext
   result = inContext.theWork()
  File "/usr/lib64/python3.7/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
   inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/usr/lib64/python3.7/site-packages/twisted/python/context.py", line 122, in callWithContext
   return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib64/python3.7/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/usr/local/lib/python3.7/site-packages/hotness/consumers.py", line 159, in __call__
   self.handle_anitya_version_update(msg)
  File "/usr/local/lib/python3.7/site-packages/hotness/consumers.py", line 204, in handle_anitya_version_update
    self._handle_anitya_update(upstream, pname, msg)
  File "/usr/local/lib/python3.7/site-packages/hotness/consumers.py", line 324, in _handle_anitya_update
   self.bugzilla.follow_up(str(e), bz)
 File "/usr/local/lib/python3.7/site-packages/hotness/bz.py", line 140, in follow_up
   self.bugzilla._proxy.Bug.update(update)
  File "/usr/lib64/python3.7/xmlrpc/client.py", line 1112, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python3.7/site-packages/bugzilla/transport.py", line 104, in _ServerProxy__request
   self)._ServerProxy__request(methodname, params)
  File "/usr/lib64/python3.7/xmlrpc/client.py", line 1452, in __request
   verbose=self.__verbose
  File "/usr/lib/python3.7/site-packages/bugzilla/transport.py", line 201, in request
   return self._request_helper(url, request_body)
  File "/usr/lib/python3.7/site-packages/bugzilla/transport.py", line 178, in _request_helper
    response.raise_for_status()
  File "/usr/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 502 Server Error: Proxy Error for url: https://bugzilla.redhat.com/xmlrpc.cgi
[fedora_messaging.cli ERROR] Unexpected error occurred in consumer Consumer(queue=the-new-hotness, callback=<hotness.consumers.BugzillaTicketFiler object at 0x7fc29cd11908>): <twisted.python.failure.Failure requests.exceptions.HTTPError: 502 Server Error: Proxy Error for url: https://bugzilla.redhat.com/xmlrpc.cgi>
```

**Comment by amrmostafazaki** [comment]
There's a lot of possibility for this issue you can solve it by set global configuration for git command itself to use a proxy server.
another solution pass a proxy argument to "handle function" to use at git command.
so what would prefer fix ?

**Comment by Zlopez** [comment]
@amrmostafazaki In this case this was issue with proxy configuration on fedoraproject.org side. In the future I want to handle this more gracefully and prevent the crash of the-new-hotness.

**Comment by amrmostafazaki** [comment]
@Zlopez +1
