### ISSUE TITLE
No new bugs?

### ISSUE THREAD

**Issue by dschwoerer** [fedora-infra/the-new-hotness#316]
It seems there are currently no new bugs filled, last one was 2021-01-24 06:35:36 [1]

release-monitoring.org is still working, as it detected a new youtube-dl version [2]

scratch builds are enabled for youtube-dl [3]

Thanks a lot for the-new-hotness - I find it very useful :+1: 

[1] https://bugzilla.redhat.com/buglist.cgi?bug_status=NEW&bug_status=ASSIGNED&bug_status=MODIFIED&bug_status=ON_DEV&bug_status=ON_QA&bug_status=VERIFIED&bug_status=RELEASE_PENDING&bug_status=POST&classification=Fedora&columnlist=product%2Ccomponent%2Cassigned_to%2Cbug_status%2Cresolution%2Cshort_desc%2Cchangeddate%2Copendate&email1=upstream-release-monitoring%40fedoraproject.org&emailreporter1=1&emailtype1=substring&list_id=1733771&order=changeddate%20DESC%2Cbug_id%20DESC&query_format=advanced
[2] https://release-monitoring.org/project/5292/
[3] https://src.fedoraproject.org/rpms/youtube-dl

**Comment by Zlopez** [comment]
Thanks for reporting, this is probably issue with new API in Anitya, which I probably didn't tested enough before releasing :-/

**Comment by Zlopez** [comment]
For record, here is the error from pod:
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/fedora_messaging/twisted/protocol.py", line 223, in _read
    yield threads.deferToThread(consumer.callback, message)
  File "/usr/lib64/python3.8/site-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "/usr/lib64/python3.8/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/usr/lib64/python3.8/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib64/python3.8/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/usr/local/lib/python3.8/site-packages/hotness/consumers.py", line 156, in __call__
    self.handle_anitya_map_new(message)
  File "/usr/local/lib/python3.8/site-packages/hotness/consumers.py", line 226, in handle_anitya_map_new
    anitya.force_check(msg.project_id)
  File "/usr/local/lib/python3.8/site-packages/hotness/anitya.py", line 55, in force_check
    % (data["version"], data["name"])
KeyError: 'version'
```

I'm now preparing a temporary fix in place and started working on the new version of the-new-hotness that will fix this issue.

**Comment by Zlopez** [comment]
The fix is now deployed on production, I will release a new hotfix version now, just wanted to deploy it and test if it's working before releasing.

I found out why I didn't found this issue on staging env, there is some issue with koji and it just returns that the package is not in koji database, so it just drops the update and continue consuming messages.
