### ISSUE TITLE
Retired package update - rubygem-ruby_parser

### ISSUE THREAD

**Issue by Zlopez** [fedora-infra/the-new-hotness#430]
This package is retired in https://src.fedoraproject.org, but this wasn't figured out by the-new-hotness before updating the bugzilla issue and starting scratch build. This should be investigated.

Note - this happened on staging, so there could be some inconsistence between data.

Here is the log from the package processing:
```
[2022-03-30 03:23:37,606 hotness.hotness_consumer INFO] Handling anitya msg '8ab88718-58bf-4b22-a082-c8dbacda6f67'
[2022-03-30 03:23:39,189 hotness.validators.mdapi INFO] Comparing upstream 3.19.0 against repo 3.11.0-3.fc30
[2022-03-30 03:23:39,189 hotness.validators.mdapi INFO] 3.19.0 is newer than 3.11.0-3.fc30
[2022-03-30 03:23:40,219 hotness.notifiers.bugzilla INFO] There is already bug opened for previous version ''[https://bugzilla.stage.redhat.com/show_bug.cgi?id=1987197'' ](https://bugzilla.stage.redhat.com/show_bug.cgi?id=1987197%27%27). Let's update this one.
[2022-03-30 03:23:40,952 hotness.notifiers.bugzilla INFO] Updated bug: 1987197
[2022-03-30 03:23:40,952 hotness.notifiers.fedora_messaging INFO] publishing topic 'hotness.update.bug.file'
[2022-03-30 03:23:40,999 hotness.builders.koji INFO] Cloning '[https://src.fedoraproject.org/rpms/rubygem-ruby_parser.git' ](https://src.fedoraproject.org/rpms/rubygem-ruby_parser.git') to '/var/tmp/thn-hnyq1jhp'
[2022-03-30 03:23:41,493 hotness.use_cases.package_scratch_build_use_case ERROR] Package scratch build use case failure
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/hotness/builders/koji.py", line 149, in build
    sp.check_output(cmd, stderr=sp.STDOUT)
  File "/usr/lib64/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib64/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/bin/rpmdev-bumpspec', '--new', '3.19.0', '-c', 'Update to 3.19.0 (#1987197)', '-u', 'Fedora Release Monitoring <release-monitoring@fedoraproject.org>', '/var/tmp/thn-hnyq1jhp/rubygem-ruby_parser.spec']' returned non-zero exit status 2.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/hotness/use_cases/package_scratch_build_use_case.py", line 56, in build
    result = self.builder.build(request.package, request.opts)
  File "/usr/local/lib/python3.9/site-packages/hotness/builders/koji.py", line 157, in build
    raise BuilderException(str(exc), std_out=std_out, std_err=std_err)
hotness.exceptions.builder_exception.BuilderException: Build failed:
Command '['/usr/bin/rpmdev-bumpspec', '--new', '3.19.0', '-c', 'Update to 3.19.0 (#1987197)', '-u', 'Fedora Release Monitoring <release-monitoring@fedoraproject.org>', '/var/tmp/thn-hnyq1jhp/rubygem-ruby_parser.spec']' returned non-zero exit status 2.

StdOut:
Usage: rpmdev-bumpspec [OPTION]... SPECFILE...

rpmdev-bumpspec bumps release tags in specfiles.

rpmdev-bumpspec: error: [Errno 2] No such file or directory: '/var/tmp/thn-hnyq1jhp/rubygem-ruby_parser.spec'


[2022-03-30 03:23:41,494 hotness.notifiers.bugzilla INFO] Bug id provided. Updating 1987197
[2022-03-30 03:23:42,131 hotness.notifiers.bugzilla INFO] Updated bug: 1987197
```

**Comment by Zlopez** [comment]
This looks like an issue in PDC, the package is retired in both https://src.fedoraproject.org and https://src.stg.fedoraproject.org, but the PDC returns that the package is still active.

Result of https://pdc.stg.fedoraproject.org/rest_api/v1/component-branches/?global_component=rubygem-ruby_parser&type=rpm&active=true
```
HTTP 200 OK
Allow: GET, POST, PUT, PATCH, DELETE, HEAD, OPTIONS
Content-Type: application/json
Vary: Accept

{
    "count": 1,
    "next": null,
    "previous": null,
    "results": [
        {
            "id": 274235,
            "global_component": "rubygem-ruby_parser",
            "name": "rawhide",
            "slas": [
                {
                    "id": 548701,
                    "sla": "rawhide",
                    "eol": "2222-01-01"
                }
            ],
            "type": "rpm",
            "active": true,
            "critical_path": false
        }
    ]
}
```

Result of https://pdc.fedoraproject.org/rest_api/v1/component-branches/?global_component=rubygem-ruby_parser&type=rpm&active=true
```
{
    "count": 4,
    "next": null,
    "previous": null,
    "results": [
        {
            "id": 520217,
            "global_component": "rubygem-ruby_parser",
            "name": "f34",
            "slas": [
                {
                    "id": 1039607,
                    "sla": "security_fixes",
                    "eol": "2022-05-17"
                },
                {
                    "id": 1039608,
                    "sla": "bug_fixes",
                    "eol": "2022-05-17"
                }
            ],
            "type": "rpm",
            "active": true,
            "critical_path": false
        },
        {
            "id": 546398,
            "global_component": "rubygem-ruby_parser",
            "name": "f35",
            "slas": [
                {
                    "id": 1091579,
                    "sla": "security_fixes",
                    "eol": "2022-11-26"
                },
                {
                    "id": 1091580,
                    "sla": "bug_fixes",
                    "eol": "2022-11-26"
                }
            ],
            "type": "rpm",
            "active": true,
            "critical_path": false
        },
        {
            "id": 574675,
            "global_component": "rubygem-ruby_parser",
            "name": "f36",
            "slas": [
                {
                    "id": 1150341,
                    "sla": "security_fixes",
                    "eol": "2023-05-16"
                },
                {
                    "id": 1150342,
                    "sla": "bug_fixes",
                    "eol": "2023-05-16"
                }
            ],
            "type": "rpm",
            "active": true,
            "critical_path": false
        },
        {
            "id": 274235,
            "global_component": "rubygem-ruby_parser",
            "name": "rawhide",
            "slas": [
                {
                    "id": 548701,
                    "sla": "rawhide",
                    "eol": "2222-01-01"
                }
            ],
            "type": "rpm",
            "active": true,
            "critical_path": false
        }
    ]
}
```

I reported the issue on https://pagure.io/releng/issue/10724 and I'm closing this ticket.
