### ISSUE TITLE
anitya login is broken (again)

### ISSUE THREAD

**Issue by ralphbean** [fedora-infra/the-new-hotness#85]
So, this is causing failures when we add new packages to pkgdb.  Fedmsg goes out and tells the-new-hotness and it tries to log in to anitya so that it can add the new mapping... but something has broken.  :( 

```python
  File "/usr/lib64/python2.7/threading.py", line 784 in __bootstrap
    self.__bootstrap_inner()
  File "/usr/lib64/python2.7/threading.py", line 811 in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 764 in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib64/python2.7/site-packages/twisted/python/threadpool.py", line 167 in _worker
    result = context.call(ctx, function, *args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/twisted/python/context.py", line 118 in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib64/python2.7/site-packages/twisted/python/context.py", line 81 in callWithContext
    return func(*args,**kw)
  File "/usr/lib/python2.7/site-packages/moksha/hub/api/consumer.py", line 193 in _work
    self.log.exception(message)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/moksha/hub/api/consumer.py", line 191, in _work
    self.consume(message)
  File "/usr/lib/python2.7/site-packages/hotness/consumers.py", line 143, in consume
    self.handle_new_package(msg, listing['package'])
  File "/usr/lib/python2.7/site-packages/hotness/consumers.py", line 446, in handle_new_package
    anitya.add_new_project(name, homepage)
  File "/usr/lib/python2.7/site-packages/hotness/anitya.py", line 358, in add_new_project
    data['csrf_token'] = soup.form.find(id='csrf_token').attrs['value']
AttributeError: 'NoneType' object has no attribute 'attrs'
```

**Comment by ralphbean** [comment]
This got fixed.
