### ISSUE TITLE
Weird message trying to initiate scratch build for ruby

### ISSUE THREAD

**Issue by ralphbean** [fedora-infra/the-new-hotness#93]
vondruch reported that hotness posted a strange error message here:  https://bugzilla.redhat.com/show_bug.cgi?id=1296452#c1

Here are the associated logs:

```
Jan 07 09:59:17 hotness01.phx2.fedoraproject.org fedmsg-hub[25795]: [2016-01-07 09:59:17][    fedmsg    INFO] Handling anitya msg u'2016-f9b011ed-d54a-4748-879f-45900e591db8'
Jan 07 09:59:18 hotness01.phx2.fedoraproject.org fedmsg-hub[25795]: [2016-01-07 09:59:18][    fedmsg    INFO] Running '/usr/bin/repoquery --config /etc/hotness-yum.conf --quiet --all --qf %{name}\t%{version}\t%{release}'
Jan 07 09:59:38 hotness01.phx2.fedoraproject.org fedmsg-hub[25795]: [2016-01-07 09:59:38][    fedmsg    INFO] Rebuilt nvr_dict with 41938 entries
Jan 07 09:59:38 hotness01.phx2.fedoraproject.org fedmsg-hub[25795]: [2016-01-07 09:59:38][    fedmsg    INFO] Comparing upstream 2.3.0 against repo 2.2.4-47.fc24
Jan 07 09:59:38 hotness01.phx2.fedoraproject.org fedmsg-hub[25795]: [2016-01-07 09:59:38][    fedmsg    INFO] OK, 2.3.0 is newer than 2.2.4-47.fc24
Jan 07 09:59:45 hotness01.phx2.fedoraproject.org fedmsg-hub[25795]: [2016-01-07 09:59:45][    fedmsg    INFO] Created bug: #1296452 NEW        - vanmeeuwen+fedora@kolabsys.com - ruby-2.3.0 is available
Jan 07 09:59:45 hotness01.phx2.fedoraproject.org fedmsg-hub[25795]: [2016-01-07 09:59:45][    fedmsg    INFO] Filed new bug 'https://bugzilla.redhat.com/show_bug.cgi?id=1296452'
Jan 07 09:59:45 hotness01.phx2.fedoraproject.org fedmsg-hub[25795]: [2016-01-07 09:59:45][    fedmsg    INFO] publishing topic 'update.bug.file'
Jan 07 09:59:45 hotness01.phx2.fedoraproject.org fedmsg-hub[25795]: [2016-01-07 09:59:45][    fedmsg    INFO] Now with #1296452, time to do koji stuff
Jan 07 09:59:45 hotness01.phx2.fedoraproject.org fedmsg-hub[25795]: [2016-01-07 09:59:45][    fedmsg    INFO] Cloning 'http://pkgs.fedoraproject.org/cgit/ruby.git' to '/var/tmp/thn-_0QUK6'
Jan 07 10:01:25 hotness01.phx2.fedoraproject.org fedmsg-hub[25795]: [2016-01-07 10:01:25][    fedmsg    INFO] Running ['/usr/bin/rpmdev-bumpspec', '--new', u'2.3.0', '-c', u'Update to 2.3.0 (#1296452)', '-u', 'Fedora Release Monitoring <release-monitoring@fedoraproject.org>', u'/var/tmp/thn-_0QUK6/ruby.spec'] in None
Jan 07 10:01:26 hotness01.phx2.fedoraproject.org fedmsg-hub[25795]: [2016-01-07 10:01:26][    fedmsg WARNING] error: line 127: Unknown tag: Suggests: rubypick
Jan 07 10:01:26 hotness01.phx2.fedoraproject.org fedmsg-hub[25795]: error: query of specfile /var/tmp/thn-_0QUK6/ruby.spec failed, can't parse
Jan 07 10:01:26 hotness01.phx2.fedoraproject.org fedmsg-hub[25795]: [2016-01-07 10:01:26][    fedmsg    INFO] Running ['fedpkg', 'sources'] in '/var/tmp/thn-_0QUK6'
Jan 07 10:01:27 hotness01.phx2.fedoraproject.org fedmsg-hub[25795]: [2016-01-07 10:01:27][    fedmsg    INFO] Running ['spectool', '-g', u'/var/tmp/thn-_0QUK6/ruby.spec'] in '/var/tmp/thn-_0QUK6'
Jan 07 10:01:28 hotness01.phx2.fedoraproject.org fedmsg-hub[25795]: [2016-01-07 10:01:28][    fedmsg WARNING] Failed to kick off scratch build.
Jan 07 10:01:28 hotness01.phx2.fedoraproject.org fedmsg-hub[25795]: [2016-01-07 10:01:28][    fedmsg WARNING] Traceback (most recent call last):
Jan 07 10:01:28 hotness01.phx2.fedoraproject.org fedmsg-hub[25795]: File "/usr/lib/python2.7/site-packages/hotness/consumers.py", line 250, in _handle_anitya_update
Jan 07 10:01:28 hotness01.phx2.fedoraproject.org fedmsg-hub[25795]: package, upstream, version, bz)
Jan 07 10:01:28 hotness01.phx2.fedoraproject.org fedmsg-hub[25795]: File "/usr/lib/python2.7/site-packages/hotness/buildsys.py", line 117, in handle
Jan 07 10:01:28 hotness01.phx2.fedoraproject.org fedmsg-hub[25795]: newfile = output.strip().split()[-1]
Jan 07 10:01:28 hotness01.phx2.fedoraproject.org fedmsg-hub[25795]: IndexError: list index out of range
Jan 07 10:01:32 hotness01.phx2.fedoraproject.org fedmsg-hub[25795]: [2016-01-07 10:01:32][    fedmsg    INFO] Followed up on bug: https://bugzilla.redhat.com/show_bug.cgi?id=1296452
```

**Comment by pypingou** [comment]
I ran into something similar the other day, when the ``split()`` returned an empty list.

**Comment by ralphbean** [comment]
No longer using spectool and rpmdev-bumpspec, so this ticket no longer applies.
